# R package PReMiuM

A manual for this package is available at [http://envirotyping.readthedocs.io/en/latest/manual/](http://envirotyping.readthedocs.io/en/latest/manual/)

See the package's page on CRAN with the latest released version: [https://cran.r-project.org/web/packages/PReMiuM/index.html](https://cran.r-project.org/web/packages/PReMiuM/index.html)

## Some papers about or using PReMiuM:

- Coker E., Liverani S., Su J. G. and J. Molitor (2018) Multi-Pollutant Modeling Through
Examination of Susceptible Subpopulations Using Profile Regression. Current Environmental
Health Reports (to appear).

- Liverani S., Lavigne A. and Blangiardo M. (2016) Modelling collinear and spatially correlated
data. Spatial and Spatio-temporal Epidemiology 18, 63-73.D R S ILVIA L IVERANI

- Mattei F., Liverani S., Guida F., Matrat M., Cenée S., Sanchez M., Luce D., Richardson S.,
Stücker I., and the Icare Study Group. (2016) A multidimensional analysis of the effect of
occupational exposure to organic solvents on lung cancer risk: the ICARE study. Occupational
and Environmental Medicine 73 (6), 368-377.

- Coker E., Liverani S., Ghosh J., Jerrett M., Beckerman B., Su J., Li A., Ritz B., Molitor J. (2016)
Multipollutant Exposure Profiles Associated with Term Low Birth Weight in Los Angeles County.
Environment International, 91, 1-13.

- Coker E., Jerrett M., Ghosh J., Gomez-Rubio V., Beckerman B., Cockburn M., Liverani S., Su
J., Li A., Ritz B., Molitor J. (2015). Geography of Risk: Modeling Spatial Effects of Air Pollutants
on Preterm Birth and Low Birth Weight in Los Angeles County. Environmental Research 142,
354-364.

- Pirani, M., Best, N., Blangiardo, M., Liverani, S., Atkinson, R. W., and G. W. Fuller (2015)
Analysing the health effects of simultaneous exposure to physical and chemical properties of
airborne particles. Environment International, 79, 56-64.

- Liverani, S., Hastie, D. I., Azizi, L., Papathomas, M. and Richardson, S. (2015) PReMiuM: An
R package for Profile Regression Mixture Models using Dirichlet Processes. Journal of
Statistical Software, 64(7), 1-30.

- Hastie, D. I., Liverani, S. and Richardson, S. (2015) Sampling from Dirichlet process mixture
models with unknown concentration parameter: Mixing issues in large data implementations.
Statistics and Computing 25 (5), 1023-1037.

- Molitor, J., Brown, I. J., Papathomas, M., Molitor, N., Liverani, S., Chan, Q., Richardson, S., Van
Horn, L., Daviglus, M. L., Stamler, J. and Elliott, P. (2014) Blood pressure differences associated
with DASH-like lower sodium compared with typical American higher sodium nutrient profile:
INTERMAP USA. Hypertension 64 (6), 1198-1204.

- Hastie, D. I., Liverani, S., Azizi, L., Richardson, S. and Stucker I. (2013) A semi-parametric
approach to estimate risk functions associated with multi-dimensional exposure profiles:
application to smoking and lung cancer. BMC Medical Research Methodology. 13 (1), 129.


